### ISSUE TITLE
generator.h5 file dependency

### ISSUE THREAD

**Issue by databloom** [PacktPublishing/Generative-Adversarial-Networks-Projects#3]
Didn't see a download link for the generator.h5 file.

Traceback (most recent call last):
  File "run.py", line 371, in <module>
    **generator.load_weights("generator.h5")**
  File "/usr/local/lib/python3.5/dist-packages/keras/engine/network.py", line 1157, in load_weights
    with h5py.File(filepath, mode='r') as f:
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 394, in __init__
    swmr=swmr)
  File "/usr/local/lib/python3.5/dist-packages/h5py/_hl/files.py", line 170, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 85, in h5py.h5f.open
OSError: Unable to open file (file signature not found)

**Comment by kailashahirwar** [comment]
@databloom generator.h5 is not public. Train your own model to create generator.h5.

**Comment by databloom** [comment]
Somehow, I uncommented the mode from train to predict. 

Thanks, I'm up and running. Appreciate the support
